spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_lib
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: schooldb
    password: 12345678
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  servlet:
    context-path: /schoollib